name: "This workflow is only for Todo infra helm"

on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-init-plan:
    runs-on: spy
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.0
  
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: 7b525079-c7d5-4cd5-8737-7d191099a476
        tenant-id: 4616d612-8bc9-4839-bf28-e030beab3250
        subscription-id: 5ed71b72-e131-4c8d-8029-6d14191c6dfe
  
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
  
    - name: Terraform Init
      id: init
      run: terraform init -input=false
      working-directory: parent/dev
  
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: parent/dev
  
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      working-directory: parent/dev

  terraform-init-apply:
    needs: terraform-init-plan
    runs-on: spy
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.0

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: 7b525079-c7d5-4cd5-8737-7d191099a476
        tenant-id: 4616d612-8bc9-4839-bf28-e030beab3250
        subscription-id: 5ed71b72-e131-4c8d-8029-6d14191c6dfe

    - name: Terraform Init
      id: init
      run: terraform init -input=false
      working-directory: parent/dev
      
    - name: Terraform Apply
      id: apply
      working-directory: parent/dev
      run: terraform apply --auto-approve  
    
  
